import React from "react";

export default function About() {
  return (
    <>
      <main className="pt-24">
        {/* Hero Section */}
        <section className="relative px-margin py-xl flex flex-col items-center justify-center min-h-[409px] overflow-hidden">
          <div className="absolute inset-0 z-0">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary/10 rounded-full blur-[120px]"></div>
          </div>
          <div className="relative z-10 text-center max-w-4xl">
            <span className="font-label-caps text-label-caps text-primary mb-sm block uppercase tracking-[0.2em]">Our Identity</span>
            <h1 className="font-h1 text-[64px] leading-tight mb-md bg-gradient-to-b from-white to-slate-500 bg-clip-text text-transparent">
              About VeriText AI
            </h1>
            <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl mx-auto">
              Pioneering the standard for digital integrity in an era of synthetic information.
            </p>
          </div>
        </section>
        {/* Mission Section */}
        <section className="px-margin py-lg max-w-screen-xl mx-auto">
          <div className="glass-card inner-glow rounded-xl p-xl relative overflow-hidden group">
            <div className="absolute -right-20 -top-20 w-64 h-64 bg-primary/5 rounded-full blur-[60px] group-hover:bg-primary/10 transition-colors duration-700"></div>
            <div className="relative z-10 grid md:grid-cols-2 gap-lg items-center">
              <div>
                <h2 className="font-h2 text-h2 mb-md text-white">Our Mission</h2>
                <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
                  VeriText AI was founded on a singular principle: <span className="text-primary font-semibold">Transparency.</span> We aim to provide researchers, journalists, and developers with the definitive tools required to distinguish human creativity from machine-generated precision.
                </p>
                <div className="mt-lg flex gap-md">
                  <div className="flex items-center gap-2">
                    <span className="material-symbols-outlined text-primary" style={{ fontVariationSettings: "'FILL' 1" }}>verified</span>
                    <span className="font-label-caps text-label-caps text-slate-300">Accuracy First</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="material-symbols-outlined text-primary" style={{ fontVariationSettings: "'FILL' 1" }}>security</span>
                    <span className="font-label-caps text-label-caps text-slate-300">Absolute Privacy</span>
                  </div>
                </div>
              </div>
              <div className="relative aspect-video rounded-lg overflow-hidden border border-white/5">
                <img alt="Technology background" className="w-full h-full object-cover opacity-80" data-alt="A high-tech digital laboratory setting with floating holographic data streams and neural network visualizations. The atmosphere is sophisticated and cinematic, dominated by deep blues and purples with bright neon accents. Clean glass surfaces and soft atmospheric lighting reflect a sense of advanced intelligence and scientific rigor." src="https://lh3.googleusercontent.com/aida-public/AB6AXuDtA88MpZuIvirTz4DyUOnTXrnPuijFPxeapT94q5-e81dAymjnR3k77-vbXIhLZpCpEkb-gtNJRWcpDCK98Z-72_r-6lDAxi4yFEdAsdeWmyArrbB7bOK8MccTzXNCKwafUyfExSj4T6iYQk61-DXDxFzOHIVu3Qu4R7bJXqR6wC5iRR-jZHk1k5yFauLEJzCFrtMsrWuEXdxYfwtBnvw2Owu5apatSWS6VQBmCzz-7pqf0U9TIHqLpWZA_S8n5o0bCTtJqJHlvlmQ" />
              </div>
            </div>
          </div>
        </section>
        {/* Background Section */}
        <section className="px-margin py-lg max-w-screen-xl mx-auto grid md:grid-cols-12 gap-lg">
          <div className="md:col-span-7 flex flex-col justify-center">
            <h3 className="font-h3 text-h3 text-white mb-md">Why We Built This</h3>

            <p className="font-body-md text-body-md text-on-surface-variant mb-sm">
              As AI tools like ChatGPT and other writing assistants become widely used, it’s getting harder to tell whether content is written by a human or generated by AI. This creates challenges in education, research, and content authenticity.
            </p>

            <p className="font-body-md text-body-md text-on-surface-variant">
              Our platform was created to solve this problem. Using advanced natural language processing techniques, we analyze writing patterns and linguistic signals to help you quickly determine whether a piece of text is AI-generated or human-written.
            </p>
          </div>

          <div className="md:col-span-5 grid grid-cols-2 gap-sm">
            <div className="glass-card inner-glow rounded-xl aspect-square flex flex-col items-center justify-center p-md">
              <span className="text-h2 font-h2 text-primary">Fast</span>
              <span className="font-label-caps text-label-caps text-slate-500">Real-time Analysis</span>
            </div>

            <div className="glass-card inner-glow rounded-xl aspect-square flex flex-col items-center justify-center p-md mt-lg">
              <span className="text-h2 font-h2 text-secondary">Reliable</span>
              <span className="font-label-caps text-label-caps text-slate-500">Smart Detection</span>
            </div>
          </div>
        </section>
        {/* Why It Matters */}
        <section className="px-margin py-lg bg-surface-container-lowest">
          <div className="max-w-screen-xl mx-auto text-center mb-xl">
            <h2 className="font-h2 text-h2 text-white mb-md">Why It Matters</h2>
            <p className="font-body-md text-body-md text-on-surface-variant max-w-3xl mx-auto">
              In a digital landscape flooded with synthetic content, authenticity is the new premium. VeriText AI ensures that human-led innovation is protected and artificial agents are identified.
            </p>
          </div>
          <div className="max-w-screen-xl mx-auto grid md:grid-cols-3 gap-md">
            <div className="p-lg rounded-xl bg-surface-container border border-white/5 hover:border-primary/30 transition-all duration-300">
              <span className="material-symbols-outlined text-primary text-4xl mb-md">gavel</span>
              <h4 className="font-h3 text-xl text-white mb-sm">Legal Integrity</h4>
              <p className="font-body-sm text-body-sm text-on-surface-variant">Ensuring that legal documents and academic submissions are authentically human-authored.</p>
            </div>
            <div className="p-lg rounded-xl bg-surface-container border border-white/5 hover:border-primary/30 transition-all duration-300">
              <span className="material-symbols-outlined text-primary text-4xl mb-md">history_edu</span>
              <h4 className="font-h3 text-xl text-white mb-sm">Academic Honesty</h4>
              <p className="font-body-sm text-body-sm text-on-surface-variant">Providing educators with clear insights into student work while maintaining fairness and transparency.</p>
            </div>
            <div className="p-lg rounded-xl bg-surface-container border border-white/5 hover:border-primary/30 transition-all duration-300">
              <span className="material-symbols-outlined text-primary text-4xl mb-md">newspaper</span>
              <h4 className="font-h3 text-xl text-white mb-sm">Journalistic Truth</h4>
              <p className="font-body-sm text-body-sm text-on-surface-variant">Helping newsrooms verify sources and ensure reportage remains free from automated manipulation.</p>
            </div>
          </div>
        </section>
        {/* Tech Stack Grid */}
        <section className="px-margin py-xl max-w-screen-xl mx-auto">
          <div className="mb-lg">
            <h2 className="font-h2 text-h2 text-white mb-sm">The Tech Stack</h2>
            <p className="font-body-md text-body-md text-on-surface-variant">High-performance engineering for real-time analysis.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-md">
            {/* BERT Card */}
            <div className="glass-card inner-glow rounded-xl p-md flex flex-col gap-md hover:scale-[1.02] transition-transform">
              <div className="w-12 h-12 rounded-lg bg-blue-500/10 flex items-center justify-center">
                <span className="material-symbols-outlined text-blue-400">psychology</span>
              </div>
              <div>
                <h4 className="font-h3 text-xl text-white">BERT</h4>
                <p className="font-body-sm text-body-sm text-on-surface-variant mt-xs">For contextual neural analysis and deep semantic understanding of text structures.</p>
              </div>
            </div>
            {/* PyTorch Card */}
            <div className="glass-card inner-glow rounded-xl p-md flex flex-col gap-md hover:scale-[1.02] transition-transform">
              <div className="w-12 h-12 rounded-lg bg-purple-500/10 flex items-center justify-center">
                <span className="material-symbols-outlined text-purple-400">memory</span>
              </div>
              <div>
                <h4 className="font-h3 text-xl text-white">PyTorch</h4>
                <p className="font-body-sm text-body-sm text-on-surface-variant mt-xs">Powering our deep learning models with industry-standard computational efficiency.</p>
              </div>
            </div>
            {/* Modern UI Card */}
            <div className="glass-card inner-glow rounded-xl p-md flex flex-col gap-md hover:scale-[1.02] transition-transform">
              <div className="w-12 h-12 rounded-lg bg-emerald-500/10 flex items-center justify-center">
                <span className="material-symbols-outlined text-emerald-400">web</span>
              </div>
              <div>
                <h4 className="font-h3 text-xl text-white">Modern Web UI</h4>
                <p className="font-body-sm text-body-sm text-on-surface-variant mt-xs">Built for a seamless, low-latency user experience across all devices and platforms.</p>
              </div>
            </div>
          </div>
        </section>
        {/* CTA Section */}
        <section className="px-margin py-xl relative">
          <div className="max-w-4xl mx-auto glass-card inner-glow rounded-xl p-xl text-center relative overflow-hidden neon-glow-primary">
            <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-secondary/5"></div>
            <div className="relative z-10">
              <h2 className="font-h2 text-h2 text-white mb-md">Ready to verify your content?</h2>
              <p className="font-body-md text-body-md text-on-surface-variant mb-lg max-w-xl mx-auto">
                Experience the precision of our neural analysis engine. Start detecting AI signatures today with VeriText AI.
              </p>
              <button className="bg-gradient-to-r from-blue-500 to-purple-600 text-white px-xl py-md rounded-full font-bold text-lg shadow-[0_0_30px_rgba(59,130,246,0.4)] hover:shadow-[0_0_50px_rgba(59,130,246,0.6)] active:scale-95 transition-all duration-300">
                Analyze Text
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}