import React from "react";

export default function PrivacyTerms() {
  return (
    <>
      <main className="pt-32 pb-24 px-margin max-w-4xl mx-auto">
        {/* Hero Section */}
        <section className="mb-lg text-center">
          <h1 className="font-h1 text-h1 neon-text-gradient mb-sm">Legal Framework &amp; Privacy</h1>
          <p className  ="font-body-lg text-body-lg text-on-surface-variant max-w-2xl mx-auto">
            Transparency is at the core of VeriText AI. We prioritize your data sovereignty and security above all else.
          </p>
        </section>
        {/* Privacy Card */}
        <div className="glass-card rim-light rounded-xl p-lg mb-md">
          <div className="flex items-center gap-3 mb-md">
            <span className="material-symbols-outlined text-blue-400 text-3xl" data-icon="shield">shield</span>
            <h2 className="font-h2 text-h2 neon-text-gradient">Privacy</h2>
          </div>
          <div className="space-y-sm font-body-md text-on-surface-variant">
            <p>VeriText AI utilizes state-of-the-art encryption to ensure that your text inputs remain confidential. We do not sell your personal data to third parties, and all analysis is performed within a secure, isolated environment.</p>
            <p>Our commitment to privacy includes:</p>
            <ul className="list-disc list-inside space-y-xs ml-4">
              <li>End-to-end encryption for all data transmissions.</li>
              <li>Automatic anonymization of sensitive entities in analyzed text.</li>
              <li>No permanent storage of processed content unless explicitly requested for model fine-tuning.</li>
            </ul>
          </div>
        </div>
        {/* Data Usage Card (Bento-style layout for inner content) */}
        <div className="glass-card rim-light rounded-xl p-lg mb-md">
          <div className="flex items-center gap-3 mb-md">
            <span className="material-symbols-outlined text-purple-400 text-3xl" data-icon="database">database</span>
            <h2 className="font-h2 text-h2 neon-text-gradient">Data Usage</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-md">
            <div className="p-md rounded-lg bg-surface-container-low border border-outline-variant/30">
              <h3 className="font-h3 text-h3 text-primary mb-xs">Model Training</h3>
              <p className="font-body-sm text-body-sm">We only use data for training purposes when users opt-in to our "Intelligence Growth" program. Otherwise, your data is processed and purged within 24 hours.</p>
            </div>
            <div className="p-md rounded-lg bg-surface-container-low border border-outline-variant/30">
              <h3 className="font-h3 text-h3 text-secondary mb-xs">Third-Party APIs</h3>
              <p className="font-body-sm text-body-sm">When utilizing external LLM providers, all requests are proxied through our proprietary scrubbing engine to remove identifying metadata before processing.</p>
            </div>
          </div>
        </div>
        {/* Terms of Service Card */}
        <div className="glass-card rim-light rounded-xl p-lg mb-lg">
          <div className="flex items-center gap-3 mb-md">
            <span className="material-symbols-outlined text-blue-300 text-3xl" data-icon="gavel">gavel</span>
            <h2 className="font-h2 text-h2 neon-text-gradient">Terms of Service</h2>
          </div>
          <div className="space-y-sm font-body-md text-on-surface-variant">
            <p>By using VeriText AI, you agree to our fair usage policy. Our services are intended for professional and ethical text analysis. Misuse of the platform for generating harmful content or bypass of security measures will result in immediate account termination.</p>
            <div className="bg-surface-container-high/50 p-md rounded-lg border-l-4 border-primary">
              <p className="italic text-on-surface">"Users maintain 100% ownership of any intellectual property provided to or generated by VeriText AI during the subscription period."</p>
            </div>
            <p>We reserve the right to update these terms as AI regulations evolve. Significant changes will be communicated via your registered dashboard email.</p>
          </div>
        </div>
        {/* Verified Security Badge Section */}
        <div className="flex flex-col items-center justify-center pt-md">
          <div className="flex items-center gap-4 px-lg py-4 rounded-full bg-surface-container-highest border border-primary/30 shadow-[0_0_20px_rgba(59,130,246,0.15)] transition-transform hover:scale-105">
            <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center">
              <span className="material-symbols-outlined text-primary" data-icon="verified_user" style={{ fontVariationSettings: "'FILL' 1" }}>verified_user</span>
            </div>
            <div>
              <p className="font-label-caps text-label-caps text-primary uppercase tracking-widest">System Status</p>
              <p className="font-h3 text-h3 leading-none m-0">Verified Security</p>
            </div>
          </div>
          <p className="mt-md font-body-sm text-body-sm text-outline">Last Updated: {new Date().toLocaleDateString()}</p>
        </div>
      </main>
    </>
  );
}